### PR TITLE
Add g:CommandTCharMatchedColor

### PR DESCRIPTION
**Pull request by bsiddiqui**
Add option to modify CommandTCharMatched from .vimrc

### CODE REVIEW

**Comment by wincent** [comment]
Thanks. Looks reasonable!

**Comment by bsiddiqui** [comment]
@wincent think we can get this merged?

**Comment by wincent** [comment]
Yeah, I think so @bsiddiqui. Sorry to be slow to deal with it (busy at work). Will get to it shortly.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, older PRs will need to be re-rolled against `main` and target the new version, so I'm closing this one out. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

**Pull request closed without merging**
