### PR TITLE
Enable CI via GH actions

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by voxik** [comment]
Hm, not sure if it can run right from the first PR :/

**Comment by wincent** [comment]
Perms are very loose:

Screenshot 2021-03-04 -193330-3SkGrMdq@2x

So we might have to fiddle to get this working. On other GitHub actions I've made I've used triggers with explicitly branches like this:

```
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
```

not sure if it is that sensitive to the format though.

**Comment by voxik** [comment]
I think I'll start to play with this in my fork and come back once I'll be smarter ;)

**Comment by wincent** [comment]
It's running now: https://github.com/wincent/command-t/commit/73a6acaf77d9d1b847635f3f68e9f6aaa9f31c70

**Comment by wincent** [comment]
And looks like with a bit of tweaking it will work: https://github.com/wincent/command-t/runs/2033753938

My favored technique here is just to push repeatedly making psuedo-random changes until it works.

**Comment by wincent** [comment]
I reckon this line is truncated:

https://github.com/wincent/command-t/blob/73a6acaf77d9d1b847635f3f68e9f6aaa9f31c70/.github/workflows/tests.yaml#L12

And if we just append the right bits to it it will work.

**Comment by voxik** [comment]
Ah, thx ... I messed up you commit again, I'll fix it shortly

**Comment by voxik** [comment]
Wow, it is passing. That was smoother then I thought.

**Comment by wincent** [comment]
Woot! Thanks.

**Comment by voxik** [comment]
Actually, the Rake could be used instead the custom build steps. But that could be enhanced once this is merged.

**Pull request closed without merging**
